### ISSUE TITLE
history since

### ISSUE THREAD

**Issue by yetibot-admin** [yetibot/yetibot#425]

**Comment by BorisKourt** [comment]
any suggestions on how/where to start implementing this?

**Comment by devth** [comment]
Yep!

Test case where you can test queries on the history model:
- Test: https://github.com/devth/yetibot.core/blob/master/test/yetibot/core/test/models/history.clj
- Model: https://github.com/devth/yetibot.core/blob/master/src/yetibot/core/models/history.clj

Add a regex to capture optional `since` to the existing `history` command https://github.com/devth/yetibot.core/blob/master/src/yetibot/core/commands/history.clj#L59-L60

The `status` command already supports `since`. You can review its source and borrow some of the regex  and model code it uses:
https://github.com/devth/yetibot.core/blob/16fa36a274ccaf45393485c89643ef975e5c2a11/src/yetibot/core/commands/status.clj#L38-L41

Let me know if you have questions at any point and thanks for the interest in contributing!

**Comment by BorisKourt** [comment]
Will take a look through the above and give you a shout if I go for it. :)

**Comment by BorisKourt** [comment]
Sorry for the delay, looked everything over. Taking a stab at it now.

**Comment by devth** [comment]
We've since migrated from Datomic to Postgres, so this should be fairly simple with a SQL query.

**Comment by devth** [comment]
Closing in favor of #875 which consolidates a bunch of history improvements.
